version: "3"

services:
  front-end:
    build: .
    container_name: front-end
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV}
    networks:
      - front-network

networks:
  front-network:
    driver: bridge
